# Generated by Django 5.2.7 on 2025-10-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_checkout_url_payment_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=2000,
                null=True,
                verbose_name="Ссыла на оплату",
            ),
        ),
    ]
